server:
   port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  profiles:
    default: db
    
  main:
    log-startup-info: false
  
  data:
   rest:
     return-body-on-create: true
     return-body-on-update: true

  output:
    ansi:
      enabled: always
    
 
  # enable H2 web console and set url for web console
  # http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /console
      